[dependencies]
base = "0.11.1"
d3storage = "https://github.com/ragpatel8742/d3storage#94f31ce0392fc0aac73bf30c1ed714912d42144e@94f31ce0392fc0aac73bf30c1ed714912d42144e"
rand = "https://github.com/aviate-labs/rand.mo#v0.2.3"
ulid = "https://github.com/aviate-labs/ulid.mo#v0.1.3"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
"httpParser" = "https://github.com/NatLabs/http-parser.mo#v0.1.2@27cba8ed0d39387e0fb660f65909ffe2a7d54413"